demux.cpp: Fix git workflow
Fix(git workflow only):

dvb/demux.cpp:599:24: error: format ‘%d’ expects argument of type ‘int’,
but argument 4 has type ‘size_t’ {aka ‘long unsigned int’};

(cherry picked from commit 1e6f1ac5d3d3197f7607e7edbc9f75f73a04a9dc)